### PR TITLE
[Button] Update styles

### LINKED ISSUE #179: [Button] Minimal hover style is off
The `borderColor: 'transparent'` causes the hover style to appear 1px off. To fix, just apply the backgroundColor to the borderColor.

### LINKED ISSUE #195: [Button] Updating Styling + New Size
As a designer, I would like our button component to be updated to new specifications. Additionally, I would like to add a 4th size to our buttons.

Design doc: https://ca2.invisionapp.com/d/main#/console/11070131/245017896/preview

AC:
- Update the buttons to spec
- Add a 4th button size to spec

Other Considerations:
- How strict is our naming in the design vs in code? ie tiny vs extra large
- Do these design patterns change things in inputs?
- Looks like the padding is staggered for icons vs no icons. How will this work for things that have both like in dropdown-menus?

### LINKED ISSUE #212: [Button] RTL Support
Please verify Button RTL support implements desired functionality primarily with respect to Icons.  I believe that it may currently be incorrect.  

### Expected behavior

Icons are in proper positions and text/icon spacing is appropriate when viewed in a RTL language.

### Current behavior

Icons do not appear in expected locations and text/icon spacing is incorrect.

### Steps to reproduce (for bugs)

Set `theme.direction = 'rtl'`, and add the css `html { direction: rtl }`, they conflict with one another.

### Possible solution

I would expect that it would work automatically without needing to pay attention to `theme.direction`.  If anything, we might need to pay attention to css direction.  Do we even need to do anything with RTL for Button?

### Versions

| Component | Version |
| :-------- | :------ |
| Button | 1.3.0 |

### PR DESCRIPTION
**Pull request by kylegach**
### Description

- Update Button styles to match new spec, mostly affects padding & application of color
- Remove no-longer-needed Button styles (yay)
- Remove RTL styles to fix #212 
- Update mineralTheme with new color applications
- Add 'jumbo' size to Button
- Update Icon sizes to match what is used in new Button spec
- Update Button examples
- Update snapshots
- Add `pxToEm` helper to component-utils and apply to styleVariables

Closes #195; closes #179; closes #212

### Motivation and context

Better Button! Seriously, just look ⬇️ .

### Screenshots or videos, if appropriate

screen shot 2017-07-27 at 2 31 04 pm
screen shot 2017-07-27 at 2 32 35 pm

### How to test
1. `cd mineral-ui/packages/button && npm start`
1. See the new styles, use Dev Tools to confirm they match spec

### Types of changes

- Breaking change (fix or feature that would cause existing functionality to change)

The theme changed. Button also no longer has some previously-available theme variables.

### Checklist

* [x] Renders and functions properly in [all supported browsers](https://github.com/mineral-ui/mineral-ui#browser-support)
* [x] Automated tests written and passing
* [x] [Accessibility](http://webaim.org/intro) and [inclusivity](https://24ways.org/2016/what-the-heck-is-inclusive-design/) considered
* [x] Rendering performance (initial load time & 60fps) and [perceived performance](http://blog.teamtreehouse.com/perceived-performance) considered
* [x] Documentation created or updated

### How does this PR make you feel?

Push the button; do something cool

### CODE REVIEW

**Comment by kylegach** [comment]
I'll split the work out into relevant commits per-package later. I also haven't updated any snapshots yet.

File: packages/button/src/Button.js [hunk 1]
```diff
@@ -42,83 +43,71 @@ type Props = {
   /** Display a primary button */
   primary?: boolean,
   /** Available sizes */
-  size?: 'small' | 'medium' | 'large',
+  size?: 'small' | 'medium' | 'large' | 'xlarge',
```
Comment (kylegach) [inline packages/button/src/Button.js]: Should we change this to `'sm' | 'md' | 'lg' | 'xl'`, so that all options are 2 letters (and more concise)? Or is that not worth doing because `'xxl'` would break the convention?

File: packages/button/src/Button.js [hunk 2]
```diff
@@ -42,83 +43,71 @@ type Props = {
...
   Button_borderWidth: '1px',
-  Button_boxShadow: baseTheme.shadow_1,
   Button_boxShadow_focus: `0 0 0 1px ${baseTheme.borderColor_focus}`,
-  Button_boxShadow_minimal_focus: `0 0 0 1px ${baseTheme.borderColor_focus}`,
-  Button_boxShadow_primary_focus: `0 0 0 1px ${baseTheme.color_theme_100}, rgba(0,0,0,0.25) 0 2px 2px`,
-  Button_color_text: baseTheme.color_gray_80,
+  Button_color_text: baseTheme.color_gray_100,
   Button_color_text_minimal: baseTheme.color_link,
   Button_color_text_primary: baseTheme.color_text_onprimary,
   Button_fontSize: baseTheme.fontSize_ui,
```
Comment (kylegach) [inline packages/button/src/Button.js]: `Button_fontSize` is only applied to Content, so should it be `ButtonContent_fontSize`?

File: packages/button/src/Button.js [hunk 3]
```diff
@@ -339,21 +270,22 @@ export default function Button({
...
-  const rootProps = {
-    size,
-    type,
-    variant,
-    ...restProps
-  };
+  const rootProps = { size, type, variant, ...restProps };
 
-  const iconSize = size === 'large' ? 'medium' : 'small';
+  const iconSize = {
```
Comment (kylegach) [inline packages/button/src/Button.js]: Should the iconSize be applied via style instead, so that they're themeable?

File: packages/button/src/__demo__/examples/iconOnly.js [hunk 4]
```diff
@@ -29,25 +29,27 @@ export default {
...
+  scope: { Button, IconCloud, DemoLayout },
   source: `() => {
-  const icon = <IconQueue color="currentColor" />;
+  const icon = <IconCloud />;
 
   return <DemoLayout>
     {/* Icon as prop; no text. aria-label applied to Button. */}
-    <Button iconStart={icon} aria-label="Add new" />
+    <Button iconStart={icon} aria-label="Cloud" />
     {/* Icon as child; no text. aria-label applied to Button. Note that the size of the icon must be provided in this case. */}
```
Comment (kylegach) [inline packages/button/src/__demo__/examples/iconOnly.js]: This example no longer looks correct because of the new padding styles, and I didn't see an easy/straightforward way to fix it. Should we just remove it?

File: packages/button/src/__demo__/examples/circular.js [hunk 5]
```diff
@@ -29,20 +29,22 @@ export default {
   title: 'Circular Buttons',
   description:
     'Buttons can be made circular. Such Buttons should not have any text.',
```
Comment (kylegach) [inline packages/button/src/__demo__/examples/circular.js]: While I think we should still advise that circular Buttons should not have text content, they now _can_, because it no longer requires a fixed-width.

File: packages/component-utils/src/em.js [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+ */
+
+/* @flow */
+/**
+  * Helper to convert a px value to ems, relative to the base font size
+  */
+import styleVariables from './styleVariables';
+
+export default function em(value: string) {
+  return `${parseFloat(value) / parseFloat(styleVariables.fontSize_base)}em`;
```
Comment (kylegach) [inline packages/component-utils/src/em.js]: If the argument was unitless (and understood to be `px`), we could save ourselves a parseFloat here.

File: packages/component-utils/src/styleVariables.js [hunk 7]
```diff
@@ -218,6 +218,7 @@ export default {
   size_small: '3em',
```
Comment (kylegach) [inline packages/component-utils/src/styleVariables.js]: Should we convert all of these `em` values to use the `em()` helper?

File: packages/component-utils/src/em.js (hunk 6 above)
Comment (kylegach) [inline packages/component-utils/src/em.js]: For that matter, we could save the second parseFloat if `fontSize_base` was unitless, too.

File: packages/button/src/Button.js [hunk 8]
```diff
@@ -137,11 +118,7 @@ const buttonStyles = (props, baseTheme) => {
       }
     })(),
     borderColor: (() => {
-      if (props.disabled) {
-        return 'transparent';
-      } else if (props.primary) {
-        return theme.Button_borderColor_primary;
-      } else if (props.minimal) {
+      if (props.disabled || props.primary || props.minimal) {
```
Comment (coldpour) [inline packages/button/src/Button.js]: Consider making this a ternary

File: packages/button/src/Button.js (hunk 1 above)
Comment (coldpour) [inline packages/button/src/Button.js]: Jumbo

File: packages/button/src/Button.js [hunk 9]
```diff
@@ -42,53 +42,64 @@ type Props = {
...
-  Button_color_text_minimal: baseTheme.color_link,
-  Button_color_text_primary: baseTheme.color_text_onprimary,
-  Button_fontSize: baseTheme.fontSize_ui,
-  Button_fontSize_small: '1.5em',
-  Button_fontWeight: baseTheme.fontWeight_semiBold,
-  Button_padding: baseTheme.spacing_single,
-  Button_padding_large: baseTheme.spacing_double,
-  [`Button_size_${props.size}`]: baseTheme[`size_${props.size}`],
+const buttonTheme = (props, baseTheme) => {
+  const base = parseFloat(baseTheme.fontSize_base);
```
Comment (coldpour) [inline packages/button/src/Button.js]: baseFontSize or fontSize_base

File: packages/button/src/Button.js [hunk 10]
```diff
@@ -268,17 +268,18 @@ export default function Button({
...
-    type,
-    variant,
-    ...restProps
-  };
+  const rootProps = { size, type, variant, ...restProps };
 
-  const iconSize = size === 'large' ? 'medium' : 'small';
+  const iconSize = {
+    small: 'small',
+    medium: 'medium',
```
Comment (coldpour) [inline packages/button/src/Button.js]: These can just be `{ 'string' }`.

File: packages/button/src/__demo__/examples/iconOnly.js (hunk 4 above)
Comment (coldpour) [inline packages/button/src/__demo__/examples/iconOnly.js]: Maybe you could remove padding on Icon in this case with `:only-child`.

File: packages/button/src/Button.js [hunk 11]
```diff
@@ -155,8 +152,7 @@ const buttonStyles = (props, baseTheme) => {
     fontWeight: theme.Button_fontWeight,
     height: theme[`Button_size_${props.size}`],
     padding: `${parseFloat(theme[`Button_padding_${props.size}`]) -
```
Comment (coldpour) [inline packages/button/src/Button.js]: Make this a function.

File: packages/component-utils/src/em.js [hunk 12]
```diff
@@ -0,0 +1,25 @@
...
+ * limitations under the License.
+ */
+
+/* @flow */
+/**
+  * Helper to convert a px value to ems, relative to the base font size
+  */
+import styleVariables from './styleVariables';
+
+export default function em(value: string) {
```
Comment (coldpour) [inline packages/component-utils/src/em.js]: Rename to pxToEm

File: packages/component-utils/src/em.js (hunk 6 above)
Comment (coldpour) [inline packages/component-utils/src/em.js]: Argument can be unitless now that the function is named clearly.

File: packages/button/src/Button.js (hunk 3 above)
Comment (kylegach) [inline packages/button/src/Button.js]: Decided to do this later, if needed.

File: packages/button/src/__demo__/examples/iconOnly.js (hunk 4 above)
Comment (kylegach) [inline packages/button/src/__demo__/examples/iconOnly.js]: This is surprisingly hard to fix. There are three relevant cases to consider:

1. Icon-only Button, via props
2. Icon-only Button, via children
3. Text-only Button

In all three, the Icon needs padding. In (2), the Icon is inside a Content, which should not have padding... but in (3) that same Content _does_ need padding. Without inspecting the children, there’s no way to style both (2) and (3).

File: packages/button/src/Button.js (hunk 10 above)
Comment (kylegach) [inline packages/button/src/Button.js]: Nope. Parsing error.

File: packages/button/src/Button.js [hunk 13]
```diff
@@ -171,18 +147,17 @@ const buttonStyles = (props, baseTheme) => {
     cursor: props.disabled ? 'default' : 'pointer',
     fontWeight: theme.Button_fontWeight,
     height: theme[`Button_size_${props.size}`],
-    padding: props.circular
-      ? `${paddingTopBottom} 0`
-      : `${paddingTopBottom} ${paddingLeftRight}`,
+    // padding: `${parseFloat(theme[`Button_padding_${props.size}`]) -
+    //   parseFloat(pxToEm(theme.Button_borderWidth))}em`,
+
+    padding: ((
```
Comment (brentertz) [inline packages/button/src/Button.js]: Not really sure this is any more readable...

**Comment by brentertz** [comment]
Huge improvement in design aesthetic

**Comment by brentertz** [comment]
Somewhat hard to grok generated values in devTools, e.g. `padding: 0 0.2857142857142857em`

**Comment by brentertz** [comment]
Orange warning color is fugly and too close to red.  I strongly prefer the previous baby puke color.  

Seriously though, I doubt that a vision impaired person could differentiate between the danger and warning colors, which IMHO makes this an a11y issue.  Perhaps not a blocker, but should be discussed with design and/or investigated using a11y tooling.

**Comment by brentertz** [comment]
Button focus styles don’t appear to work in Safari, but they didn’t work before either.

**Comment by kylegach** [comment]
Re: Safari — This works on my machine (Mac OS 10.12.6; Safari 10.1.2), so unsure what to do, if anything.

File: packages/archetype/src/__tests__/__snapshots__/Archetype.spec.js.snap [hunk 14]
```diff
@@ -55,41 +55,41 @@ exports[`Archetype Default 1`] = `
...
+        "color_theme_70": "#1b8bcc",
+        "color_theme_80": "#0f75b0",
+        "color_theme_90": "#0a6091",
         "color_white": "#fff",
         "direction": "ltr",
         "fontFamily": "Open Sans",
         "fontFamily_monospace": "monospace",
         "fontFamily_system": "-apple-system, system-ui, BlinkMacSystemFont, \\"Segoe UI\\", Roboto, Helvetica, Arial, sans-serif, \\"Apple Color Emoji\\", \\"Segoe UI Emoji\\", \\"Segoe UI Symbol\\"",
-        "fontSize_base": "8px",
+        "fontSize_base": 8,
```
Comment (brentertz) [inline packages/archetype/src/__tests__/__snapshots__/Archetype.spec.js.snap]: 8 what?  px I know, but will others?

File: packages/button/src/Button.js (hunk 13 above)
Comment (kylegach) [inline packages/button/src/Button.js]: Agreed. I went back to the previous code and added an explanatory comment to be extra clear.

**Comment by brentertz** [comment]
Re: Safari - It is a setting in Safari

screen shot 2017-07-28 at 9 40 42 am
