### PR TITLE
[Table]: Add column sorting and row selection

### LINKED ISSUE #728: Quinoa misclassified as "Delicious Food"
### Expected behavior

Quinoa should be classified correctly.

### Current behavior

Quinoa erroneously appears in a table of "Delicious Foods". 

### Possible solution

Replace with Ice Cream, Guacamole, or Donut, perhaps even a Churro.

### Steps to reproduce (for bugs)

screen shot 2018-07-05 at 3 22 38 pm

```js
// Please paste your code here
```
</p></details>

### Version

0.36.0

### Environment

My mouth.

### LINKED ISSUE #730: [Table] component fails with error when cell content is a React element.
### Expected behavior

Cell can contain React element.

### Current behavior

`deepEqual` comparison in `DataRow.shouldComponentUpdate` fails when cell content is a React element.

screen shot 2018-07-12 at 9 30 17 am

### Possible solution

Change `shouldComponentUpdate` behavior.

### Steps to reproduce (for bugs)

1. Render table with React component in cells.
2. Re-render parent component.

### Version

0.37.0, fast-deep-equals v2.0.1

### LINKED ISSUE #734: [Table] Add column sorting and row selection
As a consumer of Table, I would like to be able to sort the columns and select some or all of its rows.

#### AC
1. Sorting
    1. Table-level (every column)
    1. Column-level
    1. Default sort
    1. onSort callback
1. Row selection
    1. Table-level
    1. Disabled rows
    1. Default selection
    1. onSelection callback
1. Both
    1. a11y
    1. i18n

#### Other Considerations
- Controlled vs. uncontrolled (may be unnecessary)

### PR DESCRIPTION
**Pull request by brentertz**
### Description

Add column sorting and row selection capabilities to the Table component

Also:
* Updates Table documentation respectively
* Converts Choice, Checkbox, and Radio components to PureComponents for improved performance.
* Adds Popover support to PropTable's default props
* Fixes #730 reported by @limscoder by swapping out our "deep equal" dependency, even though we could never actually reproduce it.

### Motivation and context

* connects #690
* closes #728
* closes #730
* closes #734

### Screenshots, videos, or demo, if appropriate

https://734-table--mineral-ui.netlify.com/components/table

### How to test

1. Visit the Table demo and try out the new column sorting and row selection capabilities

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

Fixes #730 

- New feature (non-breaking change which adds functionality)

Add column sorting and row selection capabilities to Table component

- Breaking change (fix or feature that would cause existing functionality to change)

Rename theme variables **TableColumnHeader_*** to **TableHeaderCell_***

### Checklist

* [x] Renders and functions properly in [all supported browsers](https://github.com/mineral-ui/mineral-ui#browser-support)
* [x] Automated tests written and passing
* [x] [Accessibility](http://webaim.org/intro) and [inclusivity](https://24ways.org/2016/what-the-heck-is-inclusive-design/) considered
* [x] Rendering performance (initial load time & 60fps) and [perceived performance](http://blog.teamtreehouse.com/perceived-performance) considered
* [x] Documentation created or updated
* [x] Tested in [sandbox](https://github.com/facebookincubator/create-react-app#getting-started) if new component or breaking change

### CODE REVIEW

File: src/website/app/demos/Table/bestPractices.js [hunk 1]
```diff
@@ -3,6 +3,47 @@ import React from 'react';
...
+        ]}
+        columns={[
+          { key: 'product', content: 'Product', primary: true },
+          { key: 'price', content: 'Price', textAlign: 'end' }
+        ]}
+        title="Example data"
+        hideTitle
+      />
+    )
+  },
```
Comment (VictoriaVasys) [inline src/website/app/demos/Table/bestPractices.js]: During Pagination research, I came across a couple other best practices we may want to mix in here: 
* Along with our number-alignment example, maybe add a note that if using decimals, be consistent with decimal places 
* Avoid adding units in data cells; include in header instead
* Don't use Table for data sets with a blend of text, images, and data visualizations, or content with mixed formatting; use Card instead

File: src/website/app/demos/Table/examples/selectableControlled.js [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+            const index = selected.indexOf(row);
+            const hasRow = index !== -1;
+            hasRow ? selected.splice(index, 1) : selected.push(row);
+            return { selected };
+          });
+        }
+
+        handleToggleAllRows(rows) {
+          this.setState({ selected: rows });
+        }
```
Comment (VictoriaVasys) [inline src/website/app/demos/Table/examples/selectableControlled.js]: When I click a 'select even rows' & then click the indeterminate-state checkbox, instead of selecting no rows (which I believe is expected behavior), it selects all rows. At first glance, I wasn't able to discern whether that's a side-effect of this function (or if it even matters at all since this is a controlled example), but if that's the result of a built-in functionality, may be worth a thought

File: src/website/app/demos/Table/examples/sortable.js [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+  const valueA = normalizedValue(a[key]);
+  const valueB = normalizedValue(b[key]);
+
+  return valueA < valueB ? -1 : valueA > valueB ? 1 : 0;
+};
+\`\`\`
+
+In the example below, all columns except the last one have enabled sorting and
+the Dairy column has a custom sorting function to sort by length rather than
+alphabetically.
```
Comment (VictoriaVasys) [inline src/website/app/demos/Table/examples/sortable.js]: Small wording change; replace "...all columns except the last one have enabled sorting and the Dairy column has a custom sorting function to sort by length rather than alphabetically." with something like "...sorting is enabled in all columns except for the "Protein" one. The sorting function in the "Dairy" column is custom-built to sort by length rather than alphabetically"

File: src/library/Table/TableSortableHeaderCell.js [hunk 4]
```diff
@@ -0,0 +1,198 @@
...
+    'aria-label':
+      nextDirection === 'ascending'
+        ? messages.sortColumnAscending
+        : messages.sortColumnDescending,
+    onClick: () => {
+      sortFn({ key: name, descending: nextDescending });
+    }
+  };
+  const iconHolderProps = {
+    direction: (isActiveSort && activeDirection) || 'ascending',
```
Comment (VictoriaVasys) [inline src/library/Table/TableSortableHeaderCell.js]: Something about the lack of icon change when I click a column to sort feels wrong to me. Instead of 'ascending' as our default here, could we have an icon with both arrows?

File: src/website/app/demos/Table/examples/selectable.js [hunk 5]
```diff
@@ -0,0 +1,32 @@
+/* @flow */
+import Table from '../../../../../library/Table';
+import sharedData from '../shared/data';
+
+export default {
+  id: 'selectable',
+  title: 'Selectable Rows',
+  description: `Allow users to select rows with the \`selectable\` prop.
+Rows with a \`disabled\` property set to \`true\` will render a disabled
+checkbox. You can set the initially selected rows with the
```
Comment (VictoriaVasys) [inline src/website/app/demos/Table/examples/selectable.js]: Instead of "You can set the initially selected rows with the \`defaultSelectedRows\` prop", maybe "Rows can be rendered selected on initial load with the \`defaultSelectedRows\` prop.

File: src/website/app/demos/Table/bestPractices.js (hunk 1 above)
Comment (VictoriaVasys) [reply src/website/app/demos/Table/bestPractices.js]: ^^ if we want to use that 3rd point, it should be integrated into the when/how to use instead

File: src/library/Table/TableSortableHeaderCell.js [hunk 6]
```diff
@@ -0,0 +1,198 @@
...
+      : 'ascending';
+
+  const toggle = isActiveSort || activeDirection !== nextDirection;
+  const nextDescending = toggle ? !descending : descending;
+
+  const a11yLabel = label || children;
+
+  const rootProps = {
+    ...restProps,
+    // TODO: Mac Chrome VO (others?) announces this twice?
```
Comment (VictoriaVasys) [inline src/library/Table/TableSortableHeaderCell.js]: Not sure if you got through a11y testing yet, but reminder to update/remove this comment

File: src/library/Table/Table.js [hunk 7]
```diff
@@ -48,168 +85,181 @@ type Props = {
...
 
+export type Messages = {
+  deselectAllRows: string,
+  deselectRow: string,
+  selectAllRows: string,
+  selectRow: string,
+  selectedRows: string,
+  sortColumnAscending: string,
+  sortColumnDescending: string
+};
```
Comment (VictoriaVasys) [inline src/library/Table/Table.js]: This is a really neat idea. I like it!

File: src/website/app/demos/Table/examples/sortable.js [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+  value === null || value === undefined
+    ? ''
+    : typeof value === 'string' ? value.toUpperCase() : value;
+
+const defaultSortComparator: SortComparator = (a, b, key) => {
+  const valueA = normalizedValue(a[key]);
+  const valueB = normalizedValue(b[key]);
+
+  return valueA < valueB ? -1 : valueA > valueB ? 1 : 0;
+};
```
Comment (VictoriaVasys) [inline src/website/app/demos/Table/examples/sortable.js]: I really like that you include a code snippet of our sorting function. It makes it really clear how we sort & how to customize that sort.

File: src/library/themes/createThemedComponent.js [hunk 9]
```diff
@@ -1,35 +1,28 @@
...
-  ThemedComponent.propTypes = ComponentToTheme.propTypes;
+  Wrapper.propTypes = WrappedComponent.propTypes;
 
-  ThemedComponent.displayName = `Themed(${getComponentDisplayName(
-    ComponentToTheme
-  )})`;
+  Wrapper.displayName = wrapDisplayName(WrappedComponent, 'Themed');
 
-  return withTheme(ThemedComponent);
+  return withTheme(Wrapper);
```
Comment (VictoriaVasys) [inline src/library/themes/createThemedComponent.js]: This really clarifies intention for use. Nice.

File: src/library/Table/__tests__/Table.spec.js [hunk 10]
```diff
@@ -26,4 +110,398 @@ describe('Table', () => {
...
+
+      app.setState({
+        data: [...props.data, { aa: 'aa4', ab: 'ab4', ac: 'ac4', ad: 'ad4' }]
+      });
+
+      const sortedData = app.find(TableBase).props().data;
+
+      expect(sortedData).toMatchSnapshot();
+    });
+  });
```
Comment (VictoriaVasys) [inline src/library/Table/__tests__/Table.spec.js]: These tests cover a lot of different functionality in a clear & concise way. I appreciate this work.

File: src/website/app/demos/Table/examples/selectableControlled.js (hunk 2 above)
Comment (kylegach) [reply src/website/app/demos/Table/examples/selectableControlled.js]: Good catch; thanks. Addressed this with https://github.com/mineral-ui/mineral-ui/pull/737/commits/0b006eb4a1cb455ea8a72df8b58b6c792cfd1e5d, but you should take a look at it @brentertz (which is why it's unsquashed; details in the commit message).

File: src/library/Table/TableSortableHeaderCell.js (hunk 4 above)
Comment (kylegach) [reply src/library/Table/TableSortableHeaderCell.js]: For now, I removed the arrow on hover. We'll file a follow-up story to take a better look at this.

**Comment by brentertz** [comment]
This looks good to me with the exception of the behavior discussed in https://github.com/mineral-ui/mineral-ui/issues/739.  I think that can be handled in an immediate followup story however.
