### PR TITLE
[Button] enable buttons with icon

### LINKED ISSUE #153: [Button] Text is left aligned in Safari
### Expected behavior

Button text is centered

### Current behavior

Button text is left aligned

### Steps to reproduce (for bugs)

1.  Using Safari, view the [Button demo](http://mineral-ui.com/components/button).
2.  Note that the button text is left aligned in the "full width" and "states" examples.

### Context

Noticed while browsing the site on my phone using Safari.  Verified that problem also exists in desktop browser.

### Versions

| Component | Version |
| :-------- | :------ |
| Button | 1.0.0 |

### PR DESCRIPTION
**Pull request by riley**
enable icon buttons by passing in an instance of an Icon component

https://github.com/mineral-ui/mineral-ui/issues/77

### Description
We added the ability to render an Icon in a button component by passing `<IconExample />` into a button by exposing an `icon` attribute that accepts `MnrlReactNode`. Doing it this way as opposed to passing in a string prevents the Button component from having to load every Icon component into memory (and presumably into the build).

There's no reason that we couldn't pass a string in the future once tree-shaking is working better.

connects #77
closes #153 

### Motivation and context
We had a Button and we had an Icon, it's a match made in heaven.

### Screenshots or videos, if appropriate
screen shot 2017-07-17 at 11 24 02

### How has this been tested?
- visual testing in browsers
- `npm run test`

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist

* [x] Renders and functions properly in [all supported browsers](https://github.com/mineral-ui/mineral-ui#browser-support)
* [x] Automated tests written and passing
* [x] [Accessibility](http://webaim.org/intro) and [inclusivity](https://24ways.org/2016/what-the-heck-is-inclusive-design/) considered
* [x] Rendering performance (initial load time & 60fps) and [perceived performance](http://blog.teamtreehouse.com/perceived-performance) considered
* [x] Documentation created or updated

### How does this PR make you feel?

boom headshot

### CODE REVIEW

File: packages/button/src/Button.js [hunk 1]
```diff
@@ -264,11 +263,23 @@ const Root = createStyledComponent('button', buttonStyles, {
 });
 const Content = createStyledComponent('span', contentStyles);
 
+const Inner = createStyledComponent('span', (props, theme) => ({
+  alignItems: 'center',
+  display: 'inline-flex',
+  justifyContent: 'center',
+  width: '100%',
+  '& > svg': {
```
Comment (brentertz) [inline packages/button/src/Button.js]: We should probably target this as `[role=icon]` rather than `svg`.  This way, it at least has a chance of working with other non-svg icon components.

File: packages/button/src/Button.js [hunk 2]
```diff
@@ -26,6 +26,8 @@ type Props = {
   disabled?: boolean,
   /** Stretch Button to fill its container */
   fullWidth?: boolean,
+  /** An instance of an Icon component */
+  icon?: MnrlReactNode,
```
Comment (brentertz) [inline packages/button/src/Button.js]: According to the designs, Buttons need to support icons at the start and the end.  We should verify this.  Perhaps the design is illustrating some other sort of component, such as a SplitButton?

File: packages/button/src/__demo__/examples/withIcon.js [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+/* @flow */
+import React from 'react';
+import { createStyledComponent } from '@mineral-ui/component-utils';
+import Button from '../../Button';
+import IconFeedback from '@mineral-ui/icon/dist/es/lib/IconFeedback';
```
Comment (brentertz) [inline packages/button/src/__demo__/examples/withIcon.js]: Importing via `import { IconFeedback } from '@mineral-ui/icon';` allows both `npm run build` and `npm start` to work.

File: packages/component-utils/src/componentStyleReset.js [hunk 4]
```diff
@@ -16,6 +16,7 @@
 
 /* @flow */
 export default (theme: { [string]: string } = {}) => ({
+  all: 'initial',
```
Comment (brentertz) [inline packages/component-utils/src/componentStyleReset.js]: We had this in here originally, but then Kyle removed it.  Why?  Do we want it or not?  Also, it breaks the "Icons by category" demo.

File: packages/button/src/__demo__/examples/withIcon.js [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+
+const Root = createStyledComponent('div', {
+  '& > button': {
+    marginRight: '0.5rem'
+  }
+});
+
+function Example() {
+  return (
+    <Root>
```
Comment (brentertz) [inline packages/button/src/__demo__/examples/withIcon.js]: Can we get an example of a button with only an icon and no text?  In this case, it would be important to include an aria-label or perhaps/ideally the icon title will be read by the screen-reader.

File: packages/button/src/__demo__/examples/index.js [hunk 6]
```diff
@@ -35,6 +36,7 @@ export default [
   success,
   warning,
   sizes,
+  withIcon,
```
Comment (brentertz) [inline packages/button/src/__demo__/examples/index.js]: Consider renaming to `icons`?

File: packages/button/src/__demo__/examples/withIcon.js (hunk 5 above)
Comment (brentertz) [inline packages/button/src/__demo__/examples/withIcon.js]: We should also include an example of adding an icon to a button using composition.

File: packages/button/src/Button.js (hunk 2 above)
Comment (brentertz) [inline packages/button/src/Button.js]: It may be best to support both `iconStart` and `iconEnd`.  The challenge would then be how to communicate that the primary design intent is to place icons at the start.

**Comment by brentertz** [comment]
@Riley, I am assuming that your PR will also fix https://github.com/mineral-ui/mineral-ui/issues/153, so you should “connect” it to your PR with “closes #153” if that is the case.

File: packages/button/src/__demo__/examples/icons.js [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+    marginRight: '0.5rem'
+  }
+});
+
+export default {
+  title: 'With Icon',
+  description: 'Button with Icon.',
+  scope: { Button, IconNewReleases, Root },
+  source: `
+  () => {
```
Comment (coldpour) [inline packages/button/src/__demo__/examples/icons.js]: don't start the source string with a newline because then there will be a newline at the start of the editor

File: packages/button/src/__demo__/examples/icons.js [hunk 8]
```diff
@@ -0,0 +1,50 @@
...
+      const smallIcon = <IconNewReleases size="small" color="currentColor" />;
```
Comment (coldpour) [inline packages/button/src/__demo__/examples/icons.js]: this line should only be indented 2 spaces

File: packages/button/src/__demo__/examples/icons.js [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+        <Button start={smallIcon} minimal>Do Something</Button>
+        <Button size="small" start={smallIcon}>Do Something</Button>
+        <Button size="large" start={<IconNewReleases size="medium" color="currentColor" />}>Do Something</Button>
+        {/* Button Icon, no text. ARIA label applied to Button. */}
+        <Button aria-label="New Release" start={smallIcon} />
+        {/* Button Icon as child, no text. ARIA applied to Button. */}
+        <Button primary aria-label="New Release">{smallIcon}</Button>
+      </Root>
+    }
+  `
```
Comment (coldpour) [inline packages/button/src/__demo__/examples/icons.js]: don't need the extra newline here either

File: packages/button/src/Button.js [hunk 10]
```diff
@@ -264,11 +325,15 @@ const Root = createStyledComponent('button', buttonStyles, {
...
 const Content = createStyledComponent('span', contentStyles);
 
+const Inner = createStyledComponent('span', innerStyles);
+
 /**
  * The Button component represents a clickable button.
  */
 export default function Button({
   children,
+  startIcon,
```
Comment (kylegach) [inline packages/button/src/Button.js]: iconStart and iconEnd?

File: packages/button/src/Button.js [hunk 11]
```diff
@@ -281,9 +346,17 @@ export default function Button({
...
 
+  const iconSize = size === 'large' ? 'medium' : 'small';
+  const start = startIcon && React.cloneElement(startIcon, { size: iconSize });
+  const end = endIcon && React.cloneElement(endIcon, { size: iconSize });
+
   return (
     <Root {...rootProps}>
-      <Content size={size}>{children}</Content>
+      <Inner size={size}>
+        {start}
```
Comment (kylegach) [inline packages/button/src/Button.js]: startIcon and endIcon?

File: packages/button/src/__demo__/examples/circular.js [hunk 12]
```diff
@@ -0,0 +1,48 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+/* @flow */
+import { createStyledComponent } from '@mineral-ui/component-utils';
+import Button from '../../Button';
+import { IconQueue } from '@mineral-ui/icon';
+
+const Root = createStyledComponent('div', {
```
Comment (kylegach) [inline packages/button/src/__demo__/examples/circular.js]: DemoLayout?

**Comment by coldpour** [comment]
nice updates!!
