### PR TITLE
[Checkbox] IE/Edge toggle indeterminate state on single click

### LINKED ISSUE #739: [Checkbox] IE11/Edge - indeterminate checkbox requires extra initial click to toggle
### Expected behavior

Clicking on an indeterminate checkbox should toggle to unchecked with a single click

### Current behavior

In IE11/Edge, on initial click, it takes 2 clicks to toggle the input.  Afterwards it only takes a single click to toggle.

---

https://html.spec.whatwg.org/multipage/input.html#checkbox-state-(type%3Dcheckbox)

Checkboxes can only have two "real" states: `checked` or `unchecked`. The `indeterminate` or "partially checked" state is visual only and simply masks the underlying state of the checkbox.  

The first click in IE/Edge removes the `indeterminate` mask, revealing the underlying `checked` state.  As the state has not changed, no change event is triggered.  Other browsers both remove the `indeterminate` mask and toggle the `checked` state.

### Possible solution

Likely has something to do with how `indeterminate` and `checked` are set in Checkbox.

### Steps to reproduce (for bugs)

Render this in IE11/Edge

```js
<Checkbox label="Indeterminate" value="indeterminate" defaultChecked indeterminate />
```

### Context

Trying to implement row selection in Table component and the Select All checkbox behaves unexpectedly in IE11/Edge on first click when it is indeterminate.

https://734-table--mineral-ui.netlify.com/components/table/selectable

### Version

v0.37.0

### PR DESCRIPTION
**Pull request by brentertz**
### Description

* Add support for controlled/uncontrolled indeterminate checkbox state
* Fix IE/Edge toggle indeterminate state on single click
* This update fixes the Select all checkbox in selectable Tables
* Make Table density and messages props optional to avoid propType warning

### Motivation and context

closes #739 

### Screenshots, videos, or demo, if appropriate

https://739-checkbox--mineral-ui.netlify.com/

### How to test

1. View the [selectable table](https://739-checkbox--mineral-ui.netlify.com/components/table/selectable) example in IE11 or Edge.
2. Toggle the Select All checkbox and note that it toggles correctly on a single click
3. Also note the [indeterminate checkbox](https://739-checkbox--mineral-ui.netlify.com/components/checkbox/indeterminate) example

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

    * Fixes issue where indeterminate checkboxes in IE/Edge would take 2 clicks to toggle initially

- New feature (non-breaking change which adds functionality)

    * Add support for controlled and uncontrolled indeterminate checkboxes

### Checklist
* [x] Renders and functions properly in [all supported browsers](https://github.com/mineral-ui/mineral-ui#browser-support)
* [x] Automated tests written and passing
* [x] [Accessibility](http://webaim.org/intro) and [inclusivity](https://24ways.org/2016/what-the-heck-is-inclusive-design/) considered - **[n/a]**
* [x] Rendering performance (initial load time & 60fps) and [perceived performance](http://blog.teamtreehouse.com/perceived-performance) considered - **[n/a]**
* [x] Documentation created or updated
* [x] Tested in [sandbox](https://github.com/facebookincubator/create-react-app#getting-started) if new component or breaking change

### CODE REVIEW

File: src/library/Checkbox/Checkbox.js [hunk 1]
```diff
@@ -127,4 +191,46 @@ export default class Checkbox extends PureComponent<Props> {
...
+        onChange && onChange(event);
+      }
+    }
+  };
+
+  isControlled = (prop: string) => {
+    return this.props.hasOwnProperty(prop);
+  };
+
+  getIndeterminateValue = () => {
```
Comment (VictoriaVasys) [inline src/library/Checkbox/Checkbox.js]: Since this returns a boolean & not a value, perhaps we just name it `isIndeterminate` or something similar?

File: src/library/Checkbox/Checkbox.js [hunk 2]
```diff
@@ -127,4 +191,46 @@ export default class Checkbox extends PureComponent<Props> {
...
+    return Boolean(
```
Comment (VictoriaVasys) [inline src/library/Checkbox/Checkbox.js]: Do we need to return a Boolean of the evaluated code below? Shouldn't each return a boolean on their own?

File: src/library/Checkbox/Checkbox.js [hunk 3]
```diff
@@ -127,4 +191,46 @@ export default class Checkbox extends PureComponent<Props> {
...
+
+  handleClick = (event: SyntheticInputEvent<HTMLInputElement>) => {
+    const { defaultIndeterminate, indeterminate, onChange } = this.props;
+
+    if (defaultIndeterminate || indeterminate) {
+      const nextIndeterminate = this.isControlled('indeterminate')
+        ? this.getIndeterminateValue()
+        : !this.getIndeterminateValue();
+
+      this.updateState(nextIndeterminate, nextIndeterminate);
```
Comment (VictoriaVasys) [inline src/library/Checkbox/Checkbox.js]: On first glance, this is a little confusing to me, but not sure if it's worth an extra line to indicate that checked depends on indeterminate here.

File: src/library/Checkbox/Checkbox.js (hunk 2 above)
Comment (brentertz) [reply src/library/Checkbox/Checkbox.js]: They don't return a strict boolean, as `this.props.indeterminate` is an optional param.

File: src/library/Checkbox/Checkbox.js (hunk 3 above)
Comment (brentertz) [reply src/library/Checkbox/Checkbox.js]: Yeah, I could go either way...

File: src/library/Checkbox/Checkbox.js [hunk 4]
```diff
@@ -127,4 +191,46 @@ export default class Checkbox extends PureComponent<Props> {
...
     return <Root {...rootProps} />;
   }
+
+  setInputRef = (node: HTMLInputElement) => {
+    const { inputRef } = this.props;
+    this.input = node;
+    inputRef && inputRef(node);
+  };
+
+  updateState = (indeterminate: boolean, checked: boolean) => {
```
[the remark this answers is not in the document]
Comment (brentertz) [reply src/library/Checkbox/Checkbox.js]: I hear you; valid concern.  It is still state though, just not React state.  Also, since it is updating values on both the component instance and the input, I think I'll leave it as is.
