### PR TITLE
[website] Normalize AT usage & p tags in Callout; Fix internal links

### LINKED ISSUE #632: [Website] Normalize use of AT & Callout <p> tags
As a basic user, I would like normalization of usage of the term "assistive technologies" so that it is clear and consistent.

As a Mineral UI developer, I would like normalization of the `<p>` tags in the `Callout` component to provide more efficient maintainability & consistent display of callout paragraphs whether they're used in a component or not.

**AC:**
    - [ ]  Normalize usage of “assistive technology”
    - [ ]  Normalize `<p>` inside Callout, consider title margin

### LINKED ISSUE #633: Internal links in Callouts no longer functional
Some internal links still route to `mineral-ui.com/<component-name>`; all should route to `mineral-ui.com/components/<component-name>`

### PR DESCRIPTION
**Pull request by VictoriaVasys**
### Description

* Normalize all references involving AT to 'assistive technologies'
* Normalize `<p>` tags for instances of Callout & update `<p>` styling in Callout
* Update all internal links to correctly route to components
* Change all relative links to be relative-to-the-root (as should've been done in #612)

### Motivation and context

Closes #632 
Closes #633 

### Screenshots, videos, or demo, if appropriate

Then: 
screen shot 2018-03-19 at 5 46 46 pm
screen shot 2018-03-19 at 5 20 44 pm

Now: 
screen shot 2018-03-19 at 5 48 13 pm
screen shot 2018-03-19 at 5 53 47 pm

https://632-normalization--mineral-ui.netlify.com/

### How to test

1. `cd mineral-ui && npm start`
2. Navigate to `Getting Started` page
3. Confirm that the callout content is wrapped in a paragraph
4. Repeat steps 2. & 3. for all components
5. Click internal links to ensure you are routed to `mineral-ui.com/components/<component-name>` and not `mineral-ui.com/components/<component-name>` (e.g. the first `Icons` link on http://mineral-ui.com/components/avatar)

### Types of changes

- Bug fix (non-breaking change which fixes an issue)
- Other (provide details below)

Website stuff

### Checklist

* [x] Renders and functions properly in [all supported browsers](https://github.com/mineral-ui/mineral-ui#browser-support)
* [x] Automated tests written and passing [n/a]
* [x] [Accessibility](http://webaim.org/intro) and [inclusivity](https://24ways.org/2016/what-the-heck-is-inclusive-design/) considered
* [x] Rendering performance (initial load time & 60fps) and [perceived performance](http://blog.teamtreehouse.com/perceived-performance) considered [n/a]
* [x] Documentation created or updated
* [x] Tested in [sandbox](https://github.com/facebookincubator/create-react-app#getting-started) if new component or breaking change [n/a]

### How does this PR make you feel?

Paragraph dropping

### CODE REVIEW

File: src/website/app/demos/Avatar/bestPractices.js [hunk 1]
```diff
@@ -39,8 +39,8 @@ export default [
   },
   {
     type: 'dont',
-    description: `To prevent duplicate information, hide Avatar from Assistive
-Technology (AT) with \`ariaHidden="true"\` when the associated text is
+    description: `To prevent duplicate information, hide Avatar from assistive
+technologies with \`ariaHidden="true"\` when the associated text is
```
Comment (VictoriaVasys) [inline src/website/app/demos/Avatar/bestPractices.js]: @kylegach do you think we should link to the W3 definition of assistive technologies everywhere we mention it? Probably not necessary, but might help inform our audience: https://www.w3.org/WAI/PF/aria/terms#def_at

File: src/website/app/demos/Flex/examples/Flex/direction.js [hunk 2]
```diff
@@ -32,7 +32,7 @@ Additionally, their flow can be reversed.
     the <em key={0}>visual</em> order while maintaining
     the <em key={1}>semantic</em> order. This can affect keyboard users because
     of a non-intuitive tab order as well as the order of content as announced by
-    assistive technology (AT).
+    assistive technologies.
```
Comment (VictoriaVasys) [inline src/website/app/demos/Flex/examples/Flex/direction.js]: I think maybe here we should use the word "identified" rather than "announced" since not all assistive technologies involve sound... thoughts?

File: src/website/app/demos/Form/examples/FormFieldset/basic.js [hunk 3]
```diff
@@ -8,7 +8,7 @@ export default {
   title: 'Basic Usage',
   description: `Wrap any number of [FormFields](/components/form-field) in a FormFieldset
 to semantically group them. A brief, descriptive legend is especially useful for
-users of Assistive Technology (AT), such as a screen reader.`,
+users of screen readers and other assistive technologies.`,
```
Comment (VictoriaVasys) [inline src/website/app/demos/Form/examples/FormFieldset/basic.js]: Should we leave in both or just say "assistive technologies" here?

File: src/website/app/demos/Avatar/bestPractices.js (hunk 1 above)
Comment (Mikewaite) [reply src/website/app/demos/Avatar/bestPractices.js]: Not a bad idea.

File: src/website/app/demos/Form/examples/FormFieldset/basic.js (hunk 3 above)
Comment (kylegach) [inline src/website/app/demos/Form/examples/FormFieldset/basic.js]: Nice improvement.

File: src/website/app/demos/Flex/examples/Flex/direction.js (hunk 2 above)
Comment (Mikewaite) [reply src/website/app/demos/Flex/examples/Flex/direction.js]: +1

File: src/website/app/demos/Form/examples/FormFieldset/basic.js (hunk 3 above)
Comment (Mikewaite) [reply src/website/app/demos/Form/examples/FormFieldset/basic.js]: or maybe "user of assistive technologies like screen readers."

File: src/website/app/demos/Avatar/bestPractices.js (hunk 1 above)
Comment (brentertz) [reply src/website/app/demos/Avatar/bestPractices.js]: I believe it should be `aria-hidden` rather than `ariaHidden`.

File: src/website/app/demos/Flex/examples/Flex/direction.js (hunk 2 above)
Comment (coldpour) [reply src/website/app/demos/Flex/examples/Flex/direction.js]: "recognized" perhaps

File: src/website/app/demos/Radio/examples/Radio/importSyntax.js [hunk 4]
```diff
@@ -7,11 +7,13 @@ import Radio from 'mineral-ui/Radio';
 \`\`\`
 
 <Callout title="Note">
-  Mineral UI also provides a <a href="../radio-group" key={0}>RadioGroup</a>,
-  which offers a simpler API for working with a group of Radios, and
-  a <a href="../form-field" key={1}>FormField</a> to provide an accessible label
-  and other features. Examples here omit RadioGroups and FormFields for clarity
-  and brevity.
+  <p key={0}>
```
Comment (coldpour) [inline src/website/app/demos/Radio/examples/Radio/importSyntax.js]: I don't understand the `<p key={0}>` thing. how does this help / what problem does this solve?

File: src/website/app/demos/Avatar/bestPractices.js (hunk 1 above)
Comment (kylegach) [reply src/website/app/demos/Avatar/bestPractices.js]: Aren't both true? camelCase when in JSX and hypenated when in a JS object? Not sure how we disambiguate that. Maybe sticking with what HTML uses is best, though.

File: src/website/app/demos/Radio/examples/Radio/importSyntax.js (hunk 4 above)
Comment (kylegach) [reply src/website/app/demos/Radio/examples/Radio/importSyntax.js]: Two details here:

1. Our third-party markdown parser requires keys when using JSX as children like this. Not sure why, honestly.
2. We can't just wrap all Callout in a `p` because some Callouts contain multiple `p`s and nesting a `p` inside another is invalid HTML.

File: src/website/app/demos/Avatar/bestPractices.js (hunk 1 above)
Comment (brentertz) [reply src/website/app/demos/Avatar/bestPractices.js]: No, `ariaHidden` does not work in JSX.
