### PR TITLE
[Flex,FlexItem] Flex gutter refactor & improvements; FlexItem can be a Flex

### LINKED ISSUE #706: [Flex] FlexItem children don't properly support RTL
### Expected behavior

What doesn't work below should work.

### Current behavior

Passing `marginStart` or `marginEnd` on a FlexItem child should override the gutter gap; it does not. Also, Flex is applying `marginLeft` or `marginRight` with no respect to RTL (which I _think_ matters?)

### Possible solution

Not sure yet, but it'll involve these lines: https://github.com/mineral-ui/mineral-ui/blob/master/src/library/Flex/Flex.js#L187-L188

### Steps to reproduce (for bugs)

1. Render the code below somewhere
2. In an LTR environment, A should be on the left side of the container and B on the right
3. Instead, B currently sits immediately to the right of A, a gutter gap apart
4. In a RTL environment, A should be on the right side and B on the left
5. Instead, B currently sits immediately to the left of A, a gutter gap apart

<details><summary>RenderThisSomewhere.js</summary><p>

```jsx
<Flex>
  <FlexItem>A</FlexItem>
  <FlexItem marginStart="auto">B</FlexItem>
</Flex>
```
</p></details>

### Context

Prevents overriding Flex's gutter gap with per-FlexItem margins.

### Version

v0.33.0

### LINKED ISSUE #710: [StartEnd] doesn't go to start in IE11
### Expected behavior

screen shot 2018-06-07 at 9 59 00 am

### Current behavior

screen shot 2018-06-07 at 9 58 40 am

### Possible solution

not sure

### Steps to reproduce (for bugs)

1. open IE11
2. go to http://mineral-ui.com/components/start-end/basic

<details><summary>YourFileName.js</summary><p>

```js
// Please paste your code here
```
</p></details>

### Version

0.33

### Environment

prod

### LINKED ISSUE #711: [FlexItem] Cannot easily be a flex container
### Expected behavior

While building a layout, I should be able to apply flex container styles to a FlexItem, so that I can make non-trivial things.

### Current behavior

FlexItem cannot easily be a flex container (inline styles are always a non-ideal option), which prevents making anything but the most trivial of layouts without resorting to a bunch of nested Flex & FlexItems.

### Possible solution

Instead of styling Box to make FlexItem, we could style Flex. Need to consider if it's OK & expected to make every FlexItem also a Flex, though.

### Steps to reproduce (for bugs)

1. Render the code below somewhere
2. Expect the inner-most FlexItem to be vertically-centered
3. Be disappointed

<details><summary>App.js</summary><p>

```jsx
<Flex height={100}>
  <FlexItem alignItems="center">
    I'm aligned to the top :(
  </FlexItem>
</Flex>
```
</p></details>

[Edit Mineral UI FlexItem issue repro](https://codesandbox.io/s/5x5v43y85k)

### Context

Came up while observing someone build an app layout with Mineral UI.

### Version

v0.33.0

### PR DESCRIPTION
**Pull request by kylegach**
### Description

- Refactor Flex's gutters
    - To better respect RTL and responsive properties
    - To remove the outer negative margins, which had caused layout issues for consumers and was a prerequisite for...
- Add a `flex` prop to FlexItem to compose Flex instead of Box, which makes it much easier to nest flex containers and flexed items for layout purposes
- Simplify the demo-only styles for Flex, which fixed #710 
- Add some specs for critical/complex functionality
- Update snapshots
    - Pagination snapshots were affected because it uses Flex components
    - Table snapshots were affected because the controlled examples use Flex components

### Motivation and context

Closes #706, closes #710, closes #711

### Screenshots, videos, or demo, if appropriate

https://flex-improvements--mineral-ui.netlify.com/components/flex

### How to test

1. `cd mineral-ui && npm start`
2. Navigate to [Flex](https://flex-improvements--mineral-ui.netlify.com/components/flex
) and [FlexItem](https://flex-improvements--mineral-ui.netlify.com/components/flex-item)
3. Confirm everything looks correct, specifically noting the new [flex props example](https://flex-improvements--mineral-ui.netlify.com/components/flex-item/flex-props)

### Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

Breaking: The removal of the negative margins on Flex could have impact on consumer's layout, so I marked it as a breaking change.

### Checklist

* [x] Renders and functions properly in [all supported browsers](https://github.com/mineral-ui/mineral-ui#browser-support)
* [x] Automated tests written and passing
* [x] [Accessibility](http://webaim.org/intro) and [inclusivity](https://24ways.org/2016/what-the-heck-is-inclusive-design/) considered
* [x] Rendering performance (initial load time & 60fps) and [perceived performance](http://blog.teamtreehouse.com/perceived-performance) considered
* [x] Documentation created or updated
* [x] Tested in [sandbox](https://github.com/facebookincubator/create-react-app#getting-started) if new component or breaking change

### How does this PR make you feel?

Flex

### CODE REVIEW

**Comment by kylegach** [comment]
There are a number of happo diffs, but I believe they are a result of either the lack of negative margins on Flex (expected) or the newly-simplified demo-only Flex styles (expected and inconsequential to the actual component).

File: src/website/app/demos/Flex/examples/FlexItem/flexProps.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    display: flex ? 'flex' : 'block',
+    justifyContent: justifyContent || 'flex-start'
+  })
+);
+
+export default {
+  id: 'flex-props',
+  title: 'Flex Props',
+  description: `FlexItem can optionally style the [Flex](/components/flex)
+component with the \`flex\` prop, allowing it to accept any of
```
Comment (VictoriaVasys) [inline src/website/app/demos/Flex/examples/FlexItem/flexProps.js]: You may want to call this out more clearly; maybe "The `flex` prop renders the `FlexItem` as a `Flex` container... "

File: src/website/app/demos/Flex/index.js [hunk 2]
```diff
@@ -45,6 +45,10 @@ powerful and flexible enough to be the foundation of your app's layout.`
           In addition to the props above, FlexItem also accepts all props for{' '}
           <a href="/components/box" key={0}>
             Box
+          </a>{' '}
+          and, if <code key={1}>flex</code> is <code key={2}>true</code>,{' '}
```
Comment (VictoriaVasys) [inline src/website/app/demos/Flex/index.js]: Since you use "for Box" above, it would be a little more clear with a corresponding "for Flex" here.

File: src/library/Flex/Flex.js [hunk 3]
```diff
@@ -63,60 +66,123 @@ export type Values = boolean | null | number | string;
...
+
+const pushMarginProps = ({
+  direction,
+  index,
+  gutterWidth,
+  props,
+  theme,
+  ...restProps
+}) => {
+  const flip = direction === 'row-reverse';
```
Comment (VictoriaVasys) [inline src/library/Flex/Flex.js]: This could be pulled out to decrease duplication; small change though, not critical at all

File: src/library/Flex/Flex.js [hunk 4]
```diff
@@ -63,60 +66,123 @@ export type Values = boolean | null | number | string;
...
+  marginHorizontal,
+  marginStart,
+  start,
+  theme
+}) => {
+  return (
+    getIndexedValue(start ? marginStart : marginEnd, index) ||
+    getIndexedValue(marginHorizontal, index) ||
+    getIndexedValue(margin, index) ||
+    getGutterSize(theme, gutterWidth)
```
Comment (VictoriaVasys) [inline src/library/Flex/Flex.js]: I'm a little confused about the logic here; if there is a marginStart or marginEnd (& index), then there is never a marginHorizontal? It might be helpful to discuss in person.

File: src/website/app/demos/Flex/examples/FlexItem/flexProps.js (hunk 1 above)
Comment (kylegach) [reply src/website/app/demos/Flex/examples/FlexItem/flexProps.js]: Updated like so: https://github.com/mineral-ui/mineral-ui/blob/f44b50e937a942bcb33651b8891e64536e34a8ba/src/website/app/demos/Flex/examples/FlexItem/flexProps.js#L20-L23

Comment (kylegach) [reply src/website/app/demos/Flex/examples/FlexItem/flexProps.js]: I also updated all of the box props examples to use the same "composes" language: https://github.com/mineral-ui/mineral-ui/blob/f44b50e937a942bcb33651b8891e64536e34a8ba/src/website/app/demos/Flex/examples/FlexItem/boxProps.js#L8-L11

(Only FlexItem's has that second sentence.)

File: src/website/app/demos/Flex/index.js (hunk 2 above)
Comment (kylegach) [reply src/website/app/demos/Flex/index.js]: I tried to make it even more clear, by bringing Flex, the component, before `flex`, the prop: https://github.com/mineral-ui/mineral-ui/blob/f44b50e937a942bcb33651b8891e64536e34a8ba/src/website/app/demos/Flex/index.js#L45-L52

File: src/library/Flex/Flex.js (hunk 3 above)
Comment (kylegach) [reply src/library/Flex/Flex.js]: The `direction` referenced here is a value in an array, whereas the other declaration of `flip` uses the non-array, string value, so the best I could do is make it a function, which seems overkill.

I briefly considered it anyway, as it would be nice to have that `'row-reverse'` detail in one spot, but quickly realized I'd need to refactor much of the file to be consistent in such an approach, as I regular compare against "special strings" like that. So I abandoned that. 😅

File: src/library/Flex/Flex.js (hunk 4 above)
Comment (kylegach) [reply src/library/Flex/Flex.js]: It's an order of precedence thing. If a user provides a marginStart/End, marginHorizontal, or margin prop, the top line (in the code above) wins over the next and over the next until it falls back to applying the gutter.

File: src/website/app/demos/Flex/components/Flex.js [hunk 5]
```diff
@@ -1,41 +1,15 @@
...
-      top: -4,
-      zIndex: -1
-    }
-  };
-};
-
-export default createStyledComponent(_Flex, (props) => ({
-  ...containerStyles(props)
-}));
+export default createStyledComponent(_Flex, (props) => containerStyles(props));
```
Comment (brentertz) [inline src/website/app/demos/Flex/components/Flex.js]: This could be shortened by removing the extra function wrapper.

```js
export default createStyledComponent(_Flex, containerStyles);
```

File: src/website/app/demos/Grid/components/Grid.js [hunk 6]
```diff
@@ -1,41 +1,6 @@
...
-      top: -4,
-      zIndex: -1
-    }
-  };
-};
-
-export default createStyledComponent(_Grid, (props) => ({
-  ...containerStyles(props)
-}));
+export default createStyledComponent(_Grid, (props) => containerStyles(props));
```
Comment (brentertz) [inline src/website/app/demos/Grid/components/Grid.js]: Again, this could be shortened by removing the extra function wrapper.

```js
export default createStyledComponent(_Grid, containerStyles);
```

File: src/library/Flex/Flex.js [hunk 7]
```diff
@@ -159,33 +221,31 @@ const Root = createStyledComponent(Box, styles.root, {
...
     let flexItems;
-    flexItems = Children.map(children, (child) => {
-      const {
-        breakpoints: propBreakpoints,
-        margin: propMargin,
-        marginHorizontal,
-        marginLeft,
-        marginRight
-      } = child.props;
+    flexItems = Children.map(children, (child, index) => {
```
Comment (brentertz) [inline src/library/Flex/Flex.js]: Can't this just be the following?

```js
const flexItems = Children.map...
```

File: src/library/Flex/Flex.js [hunk 8]
```diff
@@ -159,33 +221,31 @@ const Root = createStyledComponent(Box, styles.root, {
...
+      const { breakpoints: propBreakpoints, ...restChildProps } = child.props;
       let props = {
         breakpoints: propBreakpoints || breakpoints
       };
 
-      if (gutterWidth) {
-        const margin =
-          marginHorizontal || propMargin || getGutterSize(theme, gutterWidth);
+      const flexItemsCount = Children.count(children);
```
Comment (brentertz) [inline src/library/Flex/Flex.js]: Can this be moved out of the iteration so it only runs once?

File: src/library/Flex/__tests__/Flex.spec.js [hunk 9]
```diff
@@ -21,4 +47,39 @@ describe('Flex', () => {
 
     expect(flex.exists()).toEqual(true);
   });
+
+  fdescribe('gutter', () => {
```
Comment (brentertz) [inline src/library/Flex/__tests__/Flex.spec.js]: Don't forget to remove the `f`.

File: src/library/Flex/Flex.js (hunk 8 above)
Comment (kylegach) [reply src/library/Flex/Flex.js]: Good call. I had left it inside the `if (child.props)` conditional to avoid the work, but it's better to do it a possible extra one time rather than `n - 1` times.

File: src/library/Flex/__tests__/Flex.spec.js (hunk 9 above)
Comment (kylegach) [reply src/library/Flex/__tests__/Flex.spec.js]: 🤦‍♂️ . Thanks.
